### ISSUE TITLE
Does not show Pdps or dps on unique weapons

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#385] opened 2021-05-09 14:39 UTC
pdps/dps is shown on rare items but not unique weapons like paradoxia etc.

**Comment by SnosMe** [comment] 2021-07-27 17:58
Duplicate of #417

**Closed by SnosMe** 2021-07-27 17:58 UTC

**Comment by leet0rz** [comment] 2021-08-12 17:37
It is actually still an issue with total ele dps on uniques like windripper etc. It does not show in hidden either.
