### ISSUE TITLE
does not allow access to the site through the program

### ISSUE THREAD

**Issue by loagn1** [SnosMe/awakened-poe-trade#895] opened 2023-03-08 19:02 UTC
hello, I have such a problem: the program connects through its own built-in browser to poe trade or to the official site of poe, but the fact is that I can’t connect to the official site directly, only through vpn, is it possible to add a choice through which browser to connect through built-in or through the one that is installed on my computer with vpn enabled?

![Screenshot_4](https://user-images.githubusercontent.com/127343002/223810971-ac31d05a-b8b3-49e7-987a-7b4ab0bf8a2c.png)

**Comment by SnosMe** [comment] 2023-03-08 19:05
Please update https://github.com/SnosMe/awakened-poe-trade/issues/840#issuecomment-1370632844

Duplicate of #840

**Closed by SnosMe** 2023-03-08 19:05 UTC

**Comment by loagn1** [comment] 2023-03-08 19:09
I updated the version even before I wrote this message, understand that it's not about the old or new version, it's about my location geographically, where I live and play poe, I have blocked access to the poe site, so the program does not work, but as soon as I connect to the game through vpn the problem disappears

**Comment by SnosMe** [comment] 2023-03-08 19:11
What's stopping you from allowing tool traffic to go through VPN too?

**Comment by loagn1** [comment] 2023-03-08 19:14
this vpn is respected and the speed is not always enough for a comfortable game, the server sometimes lags + if you add a vpn to this, it will be a "turn-based strategy", so I'm wondering if it's possible to add such a function so that you can choose which browser to connect to site, through the built-in or through the one installed on the computer
I'm sorry if I'm not quite right, I use a translator

**Comment by loagn1** [comment] 2023-03-08 19:27
I'm afraid that all this is too complicated for me and I'm unlikely to figure it out

**Comment by SnosMe** [comment] 2023-03-08 19:30
tbh, you should write to GGG support, it's weird to block only website access, but allow playing on servers.

**Comment by loagn1** [comment] 2023-03-08 19:32
maybe they think that the game is also blocked, but if I write to them, they will find out that it works and they will definitely block it, so I won’t risk it. Okay, what can I do, thanks for the answer, I’ll have to play without this program =( (
