### ISSUE TITLE
Error: Temporarily Unavailable; Please use the New Exchange Engine

### ISSUE THREAD

**Issue by Ant1death** [SnosMe/awakened-poe-trade#626] opened 2022-05-22 09:54 UTC
Error: Temporarily Unavailable; Please use the New Exchange Engine
Every time can't price check currency, playing on ru language, but i try to swap to eng, still not wor
![awa](https://user-images.githubusercontent.com/78743356/169689753-335e93fc-d09e-425d-8897-d1baa65a4744.jpg)
k

**Comment by thisVioletHydra** [comment] 2022-05-22 10:09
> Error: Temporarily Unavailable; Please use the New Exchange Engine Every time can't price check currency, playing on ru language, but i try to swap to eng, still not wor ![awa](https://user-images.githubusercontent.com/78743356/169689753-335e93fc-d09e-425d-8897-d1baa65a4744.jpg) k

![image](https://user-images.githubusercontent.com/11839238/169690305-07175ddb-54c1-4582-8196-e28f2504a779.png)

**Comment by SnosMe** [comment] 2022-05-22 11:08
Duplicate of #607

**Closed by SnosMe** 2022-05-22 11:08 UTC
