### ISSUE TITLE
App is uninstalling itself upon close

### ISSUE THREAD

**Issue by nomis51** [SnosMe/awakened-poe-trade#1177] opened 2023-12-13 15:41 UTC
I've noticed since 2 days ago, so I believe since version 3.23.10001, that the app uninstall itself when it closes. At first I thought it maybe due to a failed auto update, that corrupted or didn't finished the installation or something, no big deal, so I simply re-installed the latest version manually, and noted that all the application settings were still present. But, it then happened two more times, with the same pattern : 
- I try to start the app through Windows start menu
- Windows tell me it doesn't exists anymore
- I check the Control Panel for installed applications and indeed the application is gone
- I check the AppData folders, the config is still there, the updater is still there, but the app is gone from where I installed it, which is `AppData/Local/Programs`, the default option when installing it
- I re-install the latest version from GitHub (was 3.23.10001 the 3 times I tried), it works fine
- I close the application, wait a bit, the Windows start menu icon disappear and the application is now gone
- If I try to re-open it instantly after closing it, the application simply never boot. I believe because it's uninstalling itself or something so it just fails to run

(Tried cleaning everything manually from AppData to make a "clean install", but the problem still occurs)

Windows 10
Version : 3.23.10001

**Comment by SnosMe** [comment] 2023-12-14 09:13
Duplicate of #36 , or even if it's not I'm no responsible for installer bugs 🤷

**Closed by SnosMe** 2023-12-14 09:13 UTC
