### ISSUE TITLE
[Request] Bulk Setting for Currency Search

### ISSUE THREAD

**Issue by livejamie** [SnosMe/awakened-poe-trade#544] opened 2022-02-15 05:31 UTC
When pricing currency, certain items are much more valuable in bulk.

This example is Shrieking Essence of Greed which overlay shows 1.8c based on a bunch of people who have listed one essence.

![image](https://user-images.githubusercontent.com/49513/153997387-9cfeaa30-7d5d-4512-b465-ab78615db1dd.png)

If I change the [minimum stock to 4](https://www.pathofexile.com/trade/exchange/Archnemesis/7XOmW2f5) the price increases to 3c/ea

[If I change the minimum stock to 10, it goes to 3.5c/ea](https://www.pathofexile.com/trade/exchange/Archnemesis/YQmY6rCY)

[If I change the minimum stock to 25, it goes to 4c/ea](https://www.pathofexile.com/trade/exchange/Archnemesis/vy7KLq9fE)

Overlay shows the stack worth 45c, but in reality, it's closer to 100c.

---

The stock button in the top left works when you select it and search again but I'd like a behavior to have that happen on initial search, it also doesn't update the numbers displayed in the overlay.

**Comment by SnosMe** [comment] 2022-02-15 08:53
> I'd like a behavior to have that happen on initial search

You can do it.
![image](https://user-images.githubusercontent.com/4292308/153261688-39a20554-f3b1-4a89-99e5-a38e2c247204.png)

---

> it also doesn't update the numbers displayed in the overlay

This price is calculated from poe.ninja data, can't make improvement in this area.

Duplicate of #532

**Closed by SnosMe** 2022-02-15 08:53 UTC
