### ISSUE TITLE
New 2.12 Update no longer reconizes any mods

### ISSUE THREAD

**Issue by hhat42** [SnosMe/awakened-poe-trade#431] opened 2021-07-28 13:04 UTC
The new 2.12 version does no longer recognize any mods. When I check map, it says "item has no mods". When I check a rare armour item, it says "1 of 1 mods" - and that one mod is the armour value of the base item. This completely breaks the makro for me.

**Comment by SnosMe** [comment] 2021-07-28 13:05
Duplicate of #430

**Closed by SnosMe** 2021-07-28 13:05 UTC
