### ISSUE TITLE
Cannot distinguish between ctrl-d and ctrl-alt-d

### ISSUE THREAD

**Issue by sclient** [SnosMe/awakened-poe-trade#29] opened 2020-01-23 00:28 UTC
So, I still use Trade macro for advanced search, and it seems your tool picks up the advanced search keypress as if it were a normal search on yours.

I should also mention, I have my flask set on d, and it doesnt properly 'catch' the keypress, so it always uses my flask.

**Comment by SnosMe** [comment] 2020-01-27 21:43
Duplicate of #4 

As a workaround
![image](https://user-images.githubusercontent.com/4292308/73216404-9aea5080-415e-11ea-86a2-458791b7bd82.png)

**Closed by SnosMe** 2020-01-27 21:43 UTC
