### ISSUE TITLE
3.20.10005 update screen blackout when price checking

### ISSUE THREAD

**Issue by cmaj7bm** [SnosMe/awakened-poe-trade#855] opened 2023-01-06 12:56 UTC
setting: windowed fullscreen
windows: 11 (latest update)
version: Awakened-PoE-Trade-Setup-3.20.10005
Before 10005, it works for no issue, yet when the reminder showed up and update to v.10005, cannot do the price check as it will become low resolution (lower and lower) and then the screen will totally back out until close the app. Tried uninstall and re-install but did not work at all.

Low reso photo:
![image](https://user-images.githubusercontent.com/122098434/211015904-052d1e7f-3b6c-40ea-8000-dc0f872bb035.png)

Black out photo
![image](https://user-images.githubusercontent.com/122098434/211016324-c63fdc8f-c7cb-40df-a2d3-a8daad19d402.png)

**Comment by SnosMe** [comment] 2023-01-08 12:25
Duplicate of #818

**Closed by SnosMe** 2023-01-08 12:25 UTC
