### ISSUE TITLE
AWP keeps pasting my clipboard instead of executing the /invite @last, /tradewith @last etc

### ISSUE THREAD

**Issue by ttei080** [SnosMe/awakened-poe-trade#1277] opened 2024-01-24 21:43 UTC
It's usually something incredibly embarassing as luck would have it. It's been persisting across versions for me, since at least June 2022.

today:
![image](https://github.com/SnosMe/awakened-poe-trade/assets/37037760/edb53f6e-d502-40ff-a127-72d286af4cb2)
june '22:
![unknown](https://github.com/SnosMe/awakened-poe-trade/assets/37037760/df9136ba-0255-4280-afb3-3a14659738fb)

it's specifically these hotkeys. I'm on win10.
![image](https://github.com/SnosMe/awakened-poe-trade/assets/37037760/0e84e015-44ed-4696-9830-ae053dd870fc)

Sometimes it works fine, as intended and instantly invites or trades with the last person to whisper me. Others, this happens. It just suddenly stops working and pastes the clipboard + the person's name appended to the end of it. Closing the app & reopening it doesn't fix it. Closing poe & reopening it doesn't fix it. Reboot does fix it.

**Comment by SnosMe** [comment] 2024-01-25 08:59
Duplicate of #1139 
The game has 120ms to process input, this is like a lot of time, or maybe you're playing game with <9 FPS ??

**Closed by SnosMe** 2024-01-25 08:59 UTC
