### ISSUE TITLE
hybrid stat mod not being recognized

### ISSUE THREAD

**Issue by sisco1986** [SnosMe/awakened-poe-trade#603] opened 2022-05-16 11:47 UTC
Item Class: Rings
Rarity: Rare
Pandemonium Twirl
Sapphire Ring
--------
Requirements:
Level: 59
--------
Item Level: 80
--------
+24% to Cold Resistance (implicit)
--------
+45 to Strength
+34 to Dexterity and Intelligence
Adds 2 to 5 Physical Damage to Attacks
+30 to Evasion Rating

![ring](https://user-images.githubusercontent.com/10096979/168586007-e66738b0-75a3-49a8-a381-930f93634acf.png)

**Comment by SnosMe** [comment] 2022-05-16 11:49
Duplicate of #537

**Closed by SnosMe** 2022-05-16 11:49 UTC
