### ISSUE TITLE
Awakened PoE Trade quit unexpectedly.

### ISSUE THREAD

**Issue by ppraisethesun** [SnosMe/awakened-poe-trade#1288] opened 2024-02-12 11:48 UTC
PoE Trade version: 3.23.10005 version on a M1 Pro Macbook. 

Getting a permission popup multiple times and an error. 
<img width="744" alt="image" src="https://github.com/SnosMe/awakened-poe-trade/assets/18067021/b0ccafcd-c133-4c55-b8a5-bfd8f3bb2430">

Permission is granted
<img width="461" alt="image" src="https://github.com/SnosMe/awakened-poe-trade/assets/18067021/ce116355-1185-4f35-a903-86dbfbbef0c4">

<img width="155" alt="image" src="https://github.com/SnosMe/awakened-poe-trade/assets/18067021/d82cf919-2264-4fb8-abc2-a41f3b170254">

(this should probably link to a log file location and not a debug screen within the app?)

Couldn't find a log file location and can't access logs cause the app won't open. Anyone have or had the same problem?

**Comment by SnosMe** [comment] 2024-02-12 12:04
Duplicate of #1153

**Closed by SnosMe** 2024-02-12 12:04 UTC
