### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by AaronBeisaw** [SnosMe/awakened-poe-trade#337] opened 2021-03-11 18:37 UTC
For all video modes poe is getting a completely black screen. Closing awakened poe trade removes black screen, reopening it brings it back. Running Manjaro latest version, this just started happening today. Not sure what other details to include.

**Comment by SnosMe** [comment] 2021-03-11 18:39
You should enable window composition. Duplicate of #185

**Closed by SnosMe** 2021-03-11 18:39 UTC

**Comment by AaronBeisaw** [comment] 2021-03-11 18:46
This is not disabled. Not sure why issue is closed before it is resolved.

**Comment by SnosMe** [comment] 2021-03-11 18:52
I've closed it because this problem is very well known, you're not the first one. Moreover, it's not even specific to this application, any transparent window will be black without enabled composition. Even tho you're saying it's enabled, I've heard how steam force disabled it for optimization... I'm not using linux, can't give more hints  😉

**Comment by AaronBeisaw** [comment] 2021-03-11 18:56
Manjaro allows you to prevent applications from forcing disable, and this is also on. This is the only application which has had any transparency issues, any even with programs not allowed to block compositing it remains a black screen. All other transparency effects work outside of this app

**Comment by AaronBeisaw** [comment] 2021-03-11 18:58
Hardware acceleration within the app seems to have been the problem. Switching this setting resolved the black screen with XRender compositor.

**Comment by SnosMe** [comment] 2021-03-11 19:18
Yeah, just wanted to say to check you didn't change it from default disabled state, it's placed under Debug for a reason 😄

**Comment by AaronBeisaw** [comment] 2021-03-14 03:19
Thank you for your help and your work :)
