### ISSUE TITLE
Auto updates fail, just remove files.

### ISSUE THREAD

**Issue by willlowther** [SnosMe/awakened-poe-trade#142] opened 2020-06-26 10:55 UTC
Every time I let the app auto updates, it simply removes the files without installing the new ones, forcing me to re-download the tool. 

The install location is default ("C:\Program Files\Awakened PoE Trade\Awakened PoE Trade.exe")

**Comment by SnosMe** [comment] 2020-06-26 10:57
Duplicate of #36

**Closed by SnosMe** 2020-06-26 10:57 UTC
