### ISSUE TITLE
Charged Compass Pricing

### ISSUE THREAD

**Issue by spikeon** [SnosMe/awakened-poe-trade#578] opened 2022-03-20 14:15 UTC
Currently this app prices all Charged Compasses the same.  It also always displays an empty list of potential trades to match too.  When opening the trade window and viewing the filter, i found out why: 

Charged compasses don't appear to have an item level, but this app is filtering by min item level 60.  If we could remove that filter, we should be able to see results of similar charged compasses in the tool.

In app view of empty list
![image](https://user-images.githubusercontent.com/6240857/159166717-3eb170c4-eb7e-4556-9732-024786882d22.png)

In trade view of filters
![image](https://user-images.githubusercontent.com/6240857/159166740-b8443c8c-37a2-4042-8be1-dc58aedfda33.png)

Proof that removing level filter produces results. 
![image](https://user-images.githubusercontent.com/6240857/159166765-86de49c9-9ae3-40a9-a72e-51d9e8cbccb9.png)

**Comment by spikeon** [comment] 2022-03-20 14:18
Furthermore, reducing the item level to 0 in the app produces results.  I believe the solution is to remove the item level calulations entirely for this item type, but making it default to 0 would be an easy fix.

![image](https://user-images.githubusercontent.com/6240857/159166857-eb98a397-2eac-4a7f-820b-ad4dada09482.png)

**Comment by spikeon** [comment] 2022-03-20 14:20
Ignore above comment, it only worked once and could not replicate it.

**Comment by SnosMe** [comment] 2022-03-20 14:59
Duplicate of #560

**Closed by SnosMe** 2022-03-20 14:59 UTC
