### ISSUE TITLE
reduced Effect of Curses on you during Flask Effect

### ISSUE THREAD

**Issue by wlastas** [SnosMe/awakened-poe-trade#768] opened 2022-10-08 11:44 UTC
![image](https://user-images.githubusercontent.com/5182065/194705691-dcaf7be2-ef73-4edf-a41c-7e0d84145e91.png)

![image](https://user-images.githubusercontent.com/5182065/194705584-a043db6c-4790-439b-ae2e-3e5211e44126.png)
the current implementation does not set the value correctly and therefore nothing is found.
![image](https://user-images.githubusercontent.com/5182065/194705594-ce5fb1c3-4d66-4b14-80c3-582319542d6b.png)
The correct request looks like this:
![image](https://user-images.githubusercontent.com/5182065/194705713-20e9dd60-5ca3-4336-a981-5d18d85b1834.png)
![image](https://user-images.githubusercontent.com/5182065/194705737-89bc9229-21e1-4641-b684-fc91393457f5.png)

```
Item Class: Utility Flasks
Rarity: Magic
Abundant Diamond Flask of the Petrel
--------
Quality: +20% (augmented)
Lasts 7,20 (augmented) Seconds
Consumes 20 of 68 (augmented) Charges on use
Currently has 0 Charges
100% increased Global Critical Strike Chance
--------
Requirements:
Level: 49
--------
Item Level: 85
--------
+28 to Maximum Charges
37% reduced Effect of Curses on you during Flask Effect
--------
Right click to drink. Can only hold charges while in belt. Refills as you kill monsters.

```

**Comment by SnosMe** [comment] 2022-10-08 11:54
ty for reporst, this is fixed but not released yet. Duplicate of #759

**Closed by SnosMe** 2022-10-08 11:54 UTC

**Comment by wlastas** [comment] 2022-10-08 12:37
ok thanks will see after update^^
