### ISSUE TITLE
Black Screen in POE when Awakened trade is open

### ISSUE THREAD

**Issue by Saul1990** [SnosMe/awakened-poe-trade#859] opened 2023-01-08 09:56 UTC
If I have Awakened trade open when I run PoE, then I get a black screen. 

If I hit the windows button and close down Awakened trade it works perfectly.

It was working fine up until today...

Any ideas?

**Comment by SnosMe** [comment] 2023-01-08 14:27
Duplicate of #818 

This was fixed, try latest version

**Closed by SnosMe** 2023-01-08 14:27 UTC
