### ISSUE TITLE
Awakened PoE Trade.exe-Entry Point Not Found

### ISSUE THREAD

**Issue by compulsion84** [SnosMe/awakened-poe-trade#923] opened 2023-04-09 07:15 UTC
running on windows 8, worked last league now i keep getting this error,
did a scan for corrupted files fresh install restart, so far no luck.

**Comment by gambitflash123** [comment] 2023-04-09 10:57
I am getting the same error on Windows 8.1, it was working for many leagues without issue.But last night after autoupdating it keeps giving me Entry Point Error.

The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Program Files\Awakened PoE Trade\Awakened PoE Trade.exe

Need help please

**Comment by Xonbikx** [comment] 2023-04-09 12:01
Same issue for me, also won win 8.1, worked last season just fine,

so far i tried reinstalling portable and installer (with and witch out any antivirus software), cleaning registry, using files installed on another pc were it works just fine and doing a roll back of my pc to like 1 week prior

dont kown if there is anything in windows event logs of the errors that could help

help appreciated

**Comment by SnosMe** [comment] 2023-04-09 12:32
Duplicate of #904

**Closed by SnosMe** 2023-04-09 12:32 UTC

**Comment by Smake** [comment] 2023-04-09 14:22
Try [this](https://github.com/SnosMe/awakened-poe-trade/issues/904#issuecomment-1501137181)
