### ISSUE TITLE
Not able to price check sextant on voidstone

### ISSUE THREAD

**Issue by dmack152** [SnosMe/awakened-poe-trade#804] opened 2022-12-18 22:48 UTC
This feature used to work but when i try it now it just shows a blank blue screen. Anyone else?

**Comment by upp3r90** [comment] 2022-12-19 20:26
Yes, same issue here.

**Comment by humanCodesThings** [comment] 2022-12-19 20:28
+1 for fix

**Comment by SnosMe** [comment] 2022-12-19 23:46
Duplicate of #800

**Closed by SnosMe** 2022-12-19 23:46 UTC

**Comment by pro4up** [comment] 2022-12-20 17:23
+1 for fix
