### ISSUE TITLE
Window does not restore focus on Linux after price check (Steam + Proton)

### ISSUE THREAD

**Issue by slvrtrn** [SnosMe/awakened-poe-trade#848] opened 2023-01-04 20:33 UTC
First of all, thanks for this amazing tool and the Linux release. This is awesome.

When using Awakened PoE trade on Fedora 37, on both Gnome and KDE (XOrg session), the main PoE window behaves awkwardly - it might lose focus or experience performance degradation. 

To me, it seems that the focus loss was caused by the fact that the price check window is not fully destroyed by hitting "Esc" - it still exists while being invisible, if it makes sense.

**Comment by SnosMe** [comment] 2023-01-04 20:59
Duplicate of #476 , linux desktop is too fractured

**Closed by SnosMe** 2023-01-04 20:59 UTC
