### ISSUE TITLE
Add ITEM Search 

### ISSUE THREAD

**Issue by YohanHannan** [SnosMe/awakened-poe-trade#401] opened 2021-05-24 17:25 UTC
Is it possible to implement items search 
Example : Tabula rasa instead of alt tabbing going into pathofexile.com/trade

**Comment by SnosMe** [comment] 2021-05-25 09:34
I don't see how pressing `Alt + Tab` is worse than pressing some `xKey + yKey` if this would be implemented. Awakened  trade doesn't work in Fullscreen, so no advantage here too. Browser will always be superior to what I can make: it has tabs, has bookmarks (synchronized), supports extensions (like "BetterTrading" or extension that shows the stats changed if you would equip this item using PoB right on trade website). Memory usage also same. 

There is #164 however, that can be useful in pricing alt Gems in Heist (because you can't Ctrl+C on curio display).

---

Current built-in browser for price check exists for: debugging network errors (and blocks by CAPTCHA), sign in on trade website, tweak filters in rare cases (eg when filter is not implemented yet). It's useful because you see item on right side, this is your context. On the other hand search for item you don't have doesn't have any context, browser is the right place (or poe.ninja).

Duplicate of #164

**Closed by SnosMe** 2021-05-25 09:34 UTC
