### ISSUE TITLE
Linux i3wm/sway: game client is not focused when clicking background

### ISSUE THREAD

**Issue by LuyeT** [SnosMe/awakened-poe-trade#502] opened 2021-11-18 08:59 UTC
Hi, running into an issue on both i3wm and sway (wayland fork of i3):
First of all I set the APT window to floating.
In either case clicking on the background, does not focus the game client. You can run around using the mouse, but keyboard input is blocked (can't use abilities, flasks, open menus etc). 

My workaround currently for this is moving the APT window to a workspace on secondary monitor, which works fine. I've set this to be done automatically through the config window manager config, however the automation of this only works when APT is launched. Whenever game loses focus (I switch to web browser, discord etc.) APT window closes, and when it opens again, it will do so tiled and on the same workspace as the game. This mean whenever I switch focus from game or APT, I have to:
1. Set awakened window to floating
2. move it to appropriate workspace
3. Set game render resolution back to normal (changes automatically when window shrinks)

The focus issue for tiling WMs might be out of your control, but it would be great if there was a boolean in the settings for making APT window permanent (so it can stay in place if focus is lost).

**Comment by SnosMe** [comment] 2021-11-18 09:23
Duplicate of #476

**Closed by SnosMe** 2021-11-18 09:23 UTC
