### ISSUE TITLE
Not showing overlay after update 

### ISSUE THREAD

**Issue by micheilsgrey** [SnosMe/awakened-poe-trade#1294] opened 2024-03-06 12:50 UTC
After I updated to version `3.23.10005` the overlay is not showing. Even no info to press `Shift + Space`, same for version `3.23.10004`. All versions are showing in the tray. So I understand something changed after version `3.23.10004` and the same issue in  `3.23.10005`. Any idea why it stopped working?

Version `3.23.10003` is working fine:
![image](https://github.com/SnosMe/awakened-poe-trade/assets/8958040/56c24b8f-83d8-43ec-a90b-32b3b6d6c5f7)

**Comment by SnosMe** [comment] 2024-03-06 13:38
Yeah, there was one major change, but you're the first to have problem after 1.5months, so doubt it's related.

Anyway, install 10005 back, 
open it in browser

![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/e53f8a89-d857-4ec6-aa02-c04e012148dd)

then open DevConsole (F12)
refresh the page and finally
make a screenshot of any errors in console

**Comment by micheilsgrey** [comment] 2024-03-06 15:28
No issues in console:
![image](https://github.com/SnosMe/awakened-poe-trade/assets/8958040/b951596d-ec79-4183-ac1e-4d0fe548d7b5)

**Comment by SnosMe** [comment] 2024-04-07 13:55
Duplicate of #1306

**Closed by SnosMe** 2024-04-07 13:55 UTC

**Comment by micheilsgrey** [comment] 2024-07-19 00:27
Adding parameters to the app such as `--listen "0.0.0.0"` didn't help.
If someone is having the same issue, I fixed it by changing 1 variable in `server.ts`  
`let host = '127.0.0.1'` 
to
`let host = 'localhost' `
