### ISSUE TITLE
Cant price check rares, Only uniques.

### ISSUE THREAD

**Issue by Verastra** [SnosMe/awakened-poe-trade#546] opened 2022-02-17 04:54 UTC
As the title states, I am unable to price check rares ever since the new update. I've tried to uninstall & reinstall to no avail. I have been pondering on how to fix this for nearly 3 days now. I have exhausted my meager knowledge on how to fix this and hope you could help me with this problem. thanks in advance
![poe awakened prob](https://user-images.githubusercontent.com/99858755/154407885-f63542f0-7565-479d-a1e8-c942da512c03.jpg)
.

**Comment by SnosMe** [comment] 2022-02-17 08:06
See my comment https://github.com/SnosMe/awakened-poe-trade/issues/540#issuecomment-1038752894

Duplicate of #540

**Closed by SnosMe** 2022-02-17 08:06 UTC
