### ISSUE TITLE
Stat Value Modification (Feature Request)

### ISSUE THREAD

**Issue by esromda** [SnosMe/awakened-poe-trade#216] opened 2020-09-23 22:28 UTC
Would it be possible to change the +/- 10% threshold while price checking for stat values? Maybe allow for 2%, 5%, etc? Or even better, lock to values within a certain stat tier (Tier 1, Tier 2, etc.).

**Comment by SnosMe** [comment] 2020-09-29 11:43
duplicate of #104

**Closed** 2020-09-29 11:43 UTC
