### ISSUE TITLE
Awakened PoE Trade in OBS

### ISSUE THREAD

**Issue by PCCartem** [SnosMe/awakened-poe-trade#671] opened 2022-06-22 19:04 UTC
Hi!
How can I capture a program in OBS without capturing the screen? I've tried it in different ways, but I can't get the program to not collapse when switching to another window.

**Comment by SnosMe** [comment] 2022-06-22 19:20
APT is a transparent window, and unfortunately you can't capture such windows.

Duplicate of #299

**Closed by SnosMe** 2022-06-22 19:20 UTC
