### ISSUE TITLE
Price check only works on Legendary items

### ISSUE THREAD

**Issue by EngineersRock** [SnosMe/awakened-poe-trade#550] opened 2022-02-18 05:17 UTC
Starting a few days ago price check stopped showing results for any item that is not legendary. I tried looking at the logs but they are always empty even when the log level is set to debug. I tried uninstalling and reinstalling the app as well as rebooting the computer. I also updated to the latest geforce drivers, double checked I was running as administrator and that poe was running in windowed full screen.
![No Price check data](https://user-images.githubusercontent.com/4793099/154621807-71365d99-be9e-413e-b504-3479158d13c5.png)
![Works with Legendary item](https://user-images.githubusercontent.com/4793099/154621811-a17c10c6-093a-45aa-8ade-93b9d896c2ac.png)

**Comment by SnosMe** [comment] 2022-02-18 08:13
See my comment https://github.com/SnosMe/awakened-poe-trade/issues/540#issuecomment-1038752894

Duplicate of #540

**Closed by SnosMe** 2022-02-18 08:13 UTC
