### ISSUE TITLE
Not recognized modifier inside { brackets }

### ISSUE THREAD

**Issue by EnTart** [SnosMe/awakened-poe-trade#351] opened 2021-04-18 15:28 UTC
Heya, still got this problem event with 2.10.1. tryed both alt or ctrl but doesn't change anythings

**Comment by SnosMe** [comment] 2021-04-18 18:33
Duplicate of #346

1. This problem can't appear when using only `Ctrl` key after PoE client restart
2. There is bug in game client with ctrl+alt+c, and then pressing ctrl+c. Have no idea what's happening on your PC, waiting for fix from GGG.

**Closed by SnosMe** 2021-04-18 18:33 UTC
