### ISSUE TITLE
Overlay only intercepts mouse events on the left half of the screen

### ISSUE THREAD

**Issue by SamStonehouse** [SnosMe/awakened-poe-trade#630] opened 2022-05-24 11:47 UTC
As soon as I move my mouse onto the right side of my screen the overlay acts like the mouse isn't over it, I can't click anything and it causes the overlay to vanish if I have already moused-over it. This means I can only use the overlay for items in my stash, as my inventory is on the right.

I am using a 4k screen which could be the cause

**Comment by SnosMe** [comment] 2022-05-24 12:14
Duplicate of #597

**Comment by SnosMe** [comment] 2022-05-24 12:14
Fixed and will be in next release

**Closed by SnosMe** 2022-05-24 12:14 UTC
