### ISSUE TITLE
Black Screen on Linux

### ISSUE THREAD

**Issue by ferrosa** [SnosMe/awakened-poe-trade#428] opened 2021-07-27 13:15 UTC
Checked out the various black screen issues for Linux, in particular  #337, #304 and #185. So far none helped.

Running on Ubuntu 20.04.2 with standard gome-shell/Mutter settings, and APT v2.11.0.

APT's hardware acceleration is set to "Disabled (render on CPU)"

**Observed Behaviour**
Launch PoE in "windows fullscreen" mode, play normally.
Launch APT, once it loads the screen goes black.
I can see what is happening on the screen in the small window switching preview frame.
I can interact with the game normally by sound, just don't see anything. (APT's option "Clicking on background focuses game" is enabled).

**Expected Behaviour**
The APT overlay should be transparent, not black.

**Measures: Full Screen**
I assumed that both the PoE window as well as the APT overlay are undirected due to being fullscreen, and thus have compositing & transparency turned off.
The first step was then to turn off the fullscreen window hint.
Get the window IDs:
```
~$ xwininfo -tree -root | grep -i awakened
     0x3a00001 "Awakened PoE Trade": ("awakened-poe-trade" "awakened-poe-trade")  2560x1440+0+0  +0+0
     0x3c00003 "awakened-poe-trade": ("awakened-poe-trade" "Awakened-poe-trade")  200x200+0+0  +0+0
     0x3c00001 "awakened-poe-trade": ("awakened-poe-trade" "Awakened-poe-trade")  10x10+10+10  +10+10
```
Then check the properties of the big window:
```
~$ xprop -id 0x3a00001 | grep -i net_wm_state
_NET_WM_STATE(ATOM) = _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_FULLSCREEN
```
And then override them with any other hint (picked randomly "below", gets ignored anyway):
```
xprop -id 0x3a00001 -f _NET_WM_STATE 32a -set _NET_WM_STATE _NET_WM_STATE_BELOW
```
This doesn't immediately change anything, I have to restart the gnome-shell with Alt+F2 -> "r".
Now the APT overlay isn't fullscreen and I can see the top portion of PoE where my panel would be on the desktop (see screenshot).
![Screenshot from 2021-07-27 14-49-20](https://user-images.githubusercontent.com/20930937/127156848-c58fa4d1-69ff-436b-bad9-a60f24a429f1.png)

Unfortunately, the APT overlay is still has no transparency despite not being fullscreen anymore.

**Measures: Resizing**

Next I played a bit with the size:
```
~$ xdotool windowsize 0x3a00001 800 1200
```
This sets the black overlay to the specified size and allows me to see most of the game window (see screenshot).
![Screenshot from 2021-07-27 15-01-35](https://user-images.githubusercontent.com/20930937/127158110-31e81cc6-ef80-4db5-beb5-e658469bf537.png)
But clicking into the game immediately snaps it back to the version above (only thin stripe at the top visible).
Trying to forbid it from performing such actions with
```
~$ xprop -id 0x3a00001 -f _NET_WM_ALLOWED_ACTIONS 32a -set _NET_WM_ALLOWED_ACTIONS _NET_WM_ACTION_MOVE
```
doesn't help.
Neither does restricting the protocols (omitting sync capabilities):
```
~$ xprop -id 0x3a00001 -f WM_PROTOCOLS 32a -set WM_PROTOCOLS "WM_DELETE_WINDOW, _NET_WM_PING"
```

**What Now?**
I can't goad the APT overlay into giving up its opacity. I can't make the Mutter compositor and APT play nice together. Given that this is probably the most widely used Linux desktop configuration by a large margin, I think switching to something else is not a great recommendation.
Any further ideas?

**Comment by ferrosa** [comment] 2021-07-27 13:21
To add:
- APT used to work on my current setup a few months back.
- The Electron issue appears to be relevant only for hardware acceleration, but maybe a Electron/Chromium update in APT could still help?

**Comment by ferrosa** [comment] 2021-07-27 13:48
Fun little update.
I can use a new WM hint that is not documented on https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html but readily googleable:
```
xprop -id 0x3a00001 -format _NET_WM_WINDOW_OPACITY 32c -set _NET_WM_WINDOW_OPACITY 0xBFFFFFFF
```
This lets me make out the background well enough to click on items:
![Screenshot from 2021-07-27 15-41-14](https://user-images.githubusercontent.com/20930937/127164914-342d2ce7-ee5d-4fc5-b518-fcec644145fb.png)
The primary issue is that now both the overlay background as well as the price check popup are transparent. Splitting these apart would be APT's job I assume, they are indistinguishable from the WMs side.

Not an ideal solution, but somewhat workable for dedicated pricing sessions.

**Comment by ferrosa** [comment] 2021-07-28 13:41
Tried every APT release from 2.6.0 through 2.12.0.
2.10 and before fails with either `ReferenceError: Cannot access 'H' before initialization` or `TypeError: Cannot read property 'wmZorder' of undefined`. 
2.11 shows the same behaviour as 2.12.

**Comment by SnosMe** [comment] 2021-07-28 14:05
> sneaky auto-update function removing my AppImages

There is option to disable updates.

> The newest version that runs nicely without black screen is APT 2.10.5.

Interesting

> after realising that you can't execute an older version once you ran a newer one due to config issues

That's right, and error window exists in newer versions for this case

**Comment by SnosMe** [comment] 2021-08-03 17:12
Marking as Duplicate of #185 . Maybe this will be fixed with update Electron update.

**Comment by SnosMe** [comment] 2021-08-03 17:13
Duplicate of #185

**Closed by SnosMe** 2021-08-03 17:12 UTC

**Comment by ferrosa** [comment] 2021-08-03 21:01
What are people going to do when they encounter this black screen bug today or on the next weekend? Make a new bug report of course (because closed ones are not useful and the issue currently still exists). Also, It would be proper of me to report on the status when the next version of PoB releases, which I was planning on doing here... but I'm not going to keep posting in a closed issue, and having to make a new one that just says "#428 still a problem" is not very inviting.

Of course it's up to you how to handle this... but every company I've worked at so far only marked bugs as duplicates of already closed bugs if the current report is invalid or there is no intention to fix it. And those who close issues just for good looks are learning the drawbacks sooner or later.
I'd strongly suggest keeping one report open to track the issue, and close it only when it's resolved. It shows that you recognise the existence of the issue, and focuses the people who are having this problem at one location, while the problem exists.

**Comment by Gnarus-G** [comment] 2021-08-28 04:05
Got the same issue with KDE plasma. The culprit was the compositor's rendering backend with OpenGL 2.0; changing it to XRenderer fixed it. 
System Settings > Composition > Rendering Backend
