### ISSUE TITLE
After newest update: upon pricechecking an item or opening the settings the whole game gets greyed out.

### ISSUE THREAD

**Issue by SoftwareCreator** [SnosMe/awakened-poe-trade#843] opened 2023-01-04 11:21 UTC
As said above I just updated to the newest version (3.20.10005). When I pricecheck an item the price check starts as usual then suddenly the whole game itself gets this black-greyish overlay and even after closing the pricecheck it persists. I have to end awakened poe trade to get rid of the overlay. Also the whole overlay of either the settings or the price cheking gets very blurry. It looks like the blurryness decreases from top to bottom.
 I added a screenshot down below (I hope it works).
![Screenshot 2023-01-04 112104](https://user-images.githubusercontent.com/11524727/210544444-68479757-7302-4111-8774-5b9220bfdb1c.png)

**Comment by SnosMe** [comment] 2023-01-04 12:09
Duplicate of #818

**Closed by SnosMe** 2023-01-04 12:09 UTC

**Comment by SoftwareCreator** [comment] 2023-01-04 19:30
thanks the "-disable-gpu" flag solved it
