### ISSUE TITLE
Price chekcing does not work if an item is in the character stash, but works if its the hideout stash. 

### ISSUE THREAD

**Issue by NckyDC** [SnosMe/awakened-poe-trade#604] opened 2022-05-16 14:03 UTC
When hovering with the mouse to get the price check the panel closes. 
It works if an item is in the hideout stash.

This is from the last update of yesterday.

**Comment by SnosMe** [comment] 2022-05-16 14:18
It should be #597 
Can you record the screen with slowly moving mouse after window is visible?

**Comment by NckyDC** [comment] 2022-05-16 14:59
I must love this game and your app. managed finally....

https://youtu.be/2h3-FQEO4Fs

**Comment by sKYRRRRRRRR** [comment] 2022-05-17 07:49
Windwos' scaling is set to 100% to avoid this problem.

**Comment by NckyDC** [comment] 2022-05-17 16:23
Ok, scaling to 100% works but it also leaves my with very small text as I run a 4K monitor at 32"
And the text in the overlay is very very small.
Maybe something you can add support later so a user can see at 125% which is what I was using.

**Comment by SnosMe** [comment] 2022-05-17 23:06
Duplicate of #597

**Closed by SnosMe** 2022-05-17 23:06 UTC
Labels: bug
