### ISSUE TITLE
Pressing F5 paste the content of the clipboard in Global

### ISSUE THREAD

**Issue by krysstof** [SnosMe/awakened-poe-trade#618] opened 2022-05-18 22:55 UTC
Hello

When you press F5 a bit to early just after you connect your character (just before the text to load the item filter is shown, right after the loading screen) I noticed that your whole clipboard is pasted into the global chat !!

I got myself muted for 24h for that and I could reproduce that only with APT launched
(I had a lot text data in my clipboard, mainly about 60k of base64, you can imagine the chat after that)

it could have been some password or identification or other private data, that's not a good thing.

**Comment by SnosMe** [comment] 2022-05-19 08:21
Game has to process clipboard in 120ms, after that clipboard is restored.
Because on game load a lot of textures are loading too, PoE indeed may not be able to paste text and then Awakened restores to what it was in clipboard before (your password, pob code etc).

You can change this behavior in settings, the default prefers UX to security.
![image](https://user-images.githubusercontent.com/4292308/169247151-7dad44b6-4914-41b2-a624-cb17c7550ce4.png)

Duplicate of #199

**Closed by SnosMe** 2022-05-19 08:21 UTC
