### ISSUE TITLE
Ready and Running Popup

### ISSUE THREAD

**Issue by Jimdm3** [SnosMe/awakened-poe-trade#783] opened 2022-12-05 22:06 UTC
Is there a way to disable this? It causes my pc a lot of lag. Every time I alt+tab it pops up and causes my screen to freeze for a split second.

https://i.imgur.com/wEttKLi.png

**Comment by SnosMe** [comment] 2022-12-06 11:36
Duplicate of #772

**Closed by SnosMe** 2022-12-06 11:36 UTC
