### ISSUE TITLE
French Language not supported

### ISSUE THREAD

**Issue by AymericW** [SnosMe/awakened-poe-trade#231] opened 2020-10-02 13:55 UTC
Hi,

My gilrfriend playing poe and not understanding Poe so well puts her game in french but unfortunately the macro doesn't work in the game FR language.

This blocks her to do any kind of price checking.

Is it possible to add it somehow?

If i can help please say 👍 

Best regards,

Aymeric.

**Comment by SnosMe** [comment] 2020-10-02 14:23
Duplicate of #220

**Closed by SnosMe** 2020-10-02 14:23 UTC
