### ISSUE TITLE
Doesn't work with PoE on Geforce Now

### ISSUE THREAD

**Issue by Gisbert12843** [SnosMe/awakened-poe-trade#700] opened 2022-08-20 11:35 UTC
Seems to not realize that this is PoE too. Can't open settings now check items.

**Comment by SnosMe** [comment] 2022-08-20 14:50
You can't use it with GFN, this is indicated on the download page https://snosme.github.io/awakened-poe-trade/download

Duplicate of #170

**Closed by SnosMe** 2022-08-20 14:50 UTC

**Comment by Gisbert12843** [comment] 2022-08-23 15:21
Small Correction there's a nice workaround from a follow github user ^^ its a fairly simple marko which looks quite spooky but after reviewing and testing i can personally recommend it :) needs the steam version in geforce now though
The name of the project is "GFN_Price_Check" and below is my slightly modified version which fixes the timings for me ^^ gotta convert it to an .ahk though and ofc take a look at the source code before running anything non signed from the internet :D
[GFN_Price_Check.txt](https://github.com/SnosMe/awakened-poe-trade/files/9403909/GFN_Price_Check.txt)
h
