### ISSUE TITLE
Missing mods

### ISSUE THREAD

**Issue by ryuukk** [SnosMe/awakened-poe-trade#613] opened 2022-05-17 08:00 UTC
Hello

Sometimes, the overlay is unable to list some mods

Here ``+16 Dexterity`` is missing

![image](https://user-images.githubusercontent.com/44361234/168760421-c6e2ab5c-2dd1-47ce-a998-e3c389f8e6a2.png)

![image](https://user-images.githubusercontent.com/44361234/168760450-113e1b80-9fa3-4960-9bb2-cf56d1ff2b77.png)

```
Item Class: Rings
Rarity: Rare
Kraken Twirl
Coral Ring
--------
Requirements:
Level: 44
--------
Item Level: 85
--------
+25 to maximum Life (implicit)
--------
+33 to Strength
+16 to Dexterity
+23 to Intelligence
+1 to maximum Energy Shield
+35 to maximum Mana
```

```
Item Class: Rings
Rarity: Rare
Kraken Twirl
Coral Ring
--------
Requirements:
Level: 44
--------
Item Level: 85
--------
{ Implicit Modifier — Life }
+25(20-30) to maximum Life (implicit)
--------
{ Prefix Modifier "Cerulean" (Tier: 9) — Mana }
+35(35-39) to maximum Mana
{ Prefix Modifier "Shining" (Tier: 11) — Defences }
+1(1-3) to maximum Energy Shield
{ Suffix Modifier "of the Lynx" (Tier: 8) — Attribute }
+16(13-17) to Dexterity
{ Suffix Modifier "of the Augur" (Tier: 6) — Attribute }
+23(23-27) to Intelligence
{ Suffix Modifier "of the Goliath" (Tier: 4) — Attribute }
+33(33-37) to Strength
```

**Comment by SnosMe** [comment] 2022-05-17 08:36
Duplicate of #537

**Closed by SnosMe** 2022-05-17 08:36 UTC
