### ISSUE TITLE
Searching stash

### ISSUE THREAD

**Issue by Applefaerie** [SnosMe/awakened-poe-trade#323] opened 2021-02-06 18:07 UTC
Hi SnosMe!

First of all, great tool, takes getting used to after the AHK macro we all know and sometimes love, but IMHO it's superior. I especially dig the font size option :)

However, I really want the functionality of hitting ctrl+F while hovering over an item in your bags or stash, to put the actual item name in the search box. The AHK trade macro allows this (or maybe provides this?), and it'd be really nice to have it back. Especially when I'm hunting for a hopefully-leveled skill gem in my 50 tabs of madness.

Thanks!

**Comment by SnosMe** [comment] 2021-02-06 18:13
https://github.com/SnosMe/awakened-poe-trade/issues/200#issuecomment-672838894

Duplicate of #200

**Closed by SnosMe** 2021-02-06 18:13 UTC

**Comment by Applefaerie** [comment] 2021-02-06 19:42
Whoops! I thought I clicked the ones that sounded similar -_- sorry for the bother!
