### ISSUE TITLE
Hi: In App/Game Browser

### ISSUE THREAD

**Issue by Pumbees** [SnosMe/awakened-poe-trade#845] opened 2023-01-04 15:15 UTC
Hi, I recently just bought a brand new computer and after I installed everything, I opened the app and I can't get the browser that it has to open, it just opens up browser outside of the Awakened and I love being able to use the browser Inside. How do I get it back to being able to use it like that? Is there a way, something Im missing, Im trying to figure it out. Please help.

I mean I only ever had one issue with not being able to use it because of authentication wouldnt load proper but I use steam and it always authenticated properly with exception of one time Ii had to wait a few hours. I read something about it but I'm still wanted to figure out how to get this new setup to have it. Will stay tuned, thanks.

**Comment by SnosMe** [comment] 2023-01-04 16:01
Duplicate of #821

**Closed by SnosMe** 2023-01-04 16:01 UTC
