### ISSUE TITLE
Expedition Logbook filter

### ISSUE THREAD

**Issue by aVitomin** [SnosMe/awakened-poe-trade#553] opened 2022-02-19 23:50 UTC
Please, add property to Expedition Logbook
Because some logbook can cost more than 20c

![image](https://user-images.githubusercontent.com/11780299/154822942-5452ec03-4126-4f3d-983e-ef28fe3e7aad.png)

Price with Knights of the Sun around 70c

**Comment by SnosMe** [comment] 2022-02-20 07:29
Duplicate of #533

**Closed by SnosMe** 2022-02-20 07:29 UTC
