### ISSUE TITLE
updating removes entire program

### ISSUE THREAD

**Issue by fausing** [SnosMe/awakened-poe-trade#306] opened 2021-01-22 16:02 UTC
when the app tells me there's an update on next startup, it automatically uninstalls everything, and i have to download the new setup file from github.

**Comment by Yikez** [comment] 2021-01-23 12:13
Happens to two of us here as well.

**Comment by SnosMe** [comment] 2021-01-24 10:13
duplicate of #36

**Closed by SnosMe** 2021-01-24 10:13 UTC
