### ISSUE TITLE
Can you add this code for Korean language?

### ISSUE THREAD

**Issue by sniper-sin** [SnosMe/awakened-poe-trade#713] opened 2022-08-24 01:19 UTC
https://github.com/kyankang/awakened-poe-trade

This fork was an awakened trade for Korean, But the latest version is no longer available.
Because kyankang's awakened-poe-trade for Korean is no longer updated, So i can't use the latest 3.19 version of awakened trade.
Could you please add the corresponding source code for Korean?

**Comment by Nightblade** [comment] 2022-08-29 12:44
Very unlikely:

> Will my language be supported?
> No plans to support other languages.

**Comment by SnosMe** [comment] 2022-08-31 14:00
Duplicate of #608 

It will be the next language after ru and cn. Need to compile list of stat translation for GGG to fix first tho. So maybe next league?

**Closed by SnosMe** 2022-08-31 14:00 UTC
