### ISSUE TITLE
Compass price check has bad preset

### ISSUE THREAD

**Issue by orlp** [SnosMe/awakened-poe-trade#567] opened 2022-03-12 09:51 UTC
By default when using CTRL+D on a charged compass it selects the item level which means the search will always return 0 results. I think it'd be useful to make an exception for this item type, and prevent selecting item level when a Charged Compass is being price checked.

**Comment by SnosMe** [comment] 2022-03-12 11:47
Duplicate of #560

**Closed by SnosMe** 2022-03-12 11:47 UTC
