### ISSUE TITLE
Oauth for 3.19 will be needed. 

### ISSUE THREAD

**Issue by zombodotcom** [SnosMe/awakened-poe-trade#692] opened 2022-08-12 16:58 UTC
https://www.pathofexile.com/forum/view-thread/3293287
https://www.pathofexile.com/forum/view-thread/3293287#tradewebsitechanges

Accessing the Path of Exile: Trade website now requires you to be logged in.

**Comment by SnosMe** [comment] 2022-08-12 18:51
Thank you for your attention, everything will be fine. Duplicate of #691

**Closed by SnosMe** 2022-08-12 18:51 UTC

**Comment by zombodotcom** [comment] 2022-08-12 20:33
thanks for looking into this <3
