### ISSUE TITLE
Crashes Discord Everytime I Open Awakened POE Trade

### ISSUE THREAD

**Issue by Radizzt** [SnosMe/awakened-poe-trade#222] opened 2020-09-25 21:30 UTC
Anyone else getting their discord crashed everytime they open this?

It's a javascript error and after closing discord it always need to download another update

**Comment by SnosMe** [comment] 2020-09-29 11:27
Closing, because it is impossible to reproduce, and therefore to fix.

> javascript error

Screenshot can be helpful

**Closed by SnosMe** 2020-09-29 11:27 UTC
