### ISSUE TITLE
Item Bug

### ISSUE THREAD

**Issue by Liverslapper** [SnosMe/awakened-poe-trade#782] opened 2022-12-04 05:49 UTC
<img width="992" alt="PoEBug" src="https://user-images.githubusercontent.com/16299364/205476658-85f1a1fa-305d-4f0e-b3c8-8b30d012df8f.png">

All other items have been working fine.

**Comment by SnosMe** [comment] 2022-12-06 00:35
Duplicate of #775

**Closed by SnosMe** 2022-12-06 00:35 UTC
