### ISSUE TITLE
[eature request] See item info

### ISSUE THREAD

**Issue by noraj** [SnosMe/awakened-poe-trade#372] opened 2021-05-01 14:50 UTC
It would be awesome to have the "See item info" of PoE-trade https://github.com/PoE-TradeMacro/POE-TradeMacro#shortcuts to see advanced info of an item (min-max, pseudo attributes eg. total elemental resistances, etc.)

**Comment by SnosMe** [comment] 2021-05-01 19:53
Duplicate of #118

**Closed by SnosMe** 2021-05-01 19:53 UTC
