### ISSUE TITLE
The program crashes immediately after launch.

### ISSUE THREAD

**Issue by immellman-test** [SnosMe/awakened-poe-trade#571] opened 2022-03-15 09:17 UTC
**Hi**, the program crashes immediately after launch, but you can see the exhaust in the terminal. Can I fix it myself?
I see that there is swearing on the keyboard, and I understand that the type can't make a keyboard run? This is strange.

**config**: ubuntu 21.10, gnome-shell (40.0.4), wayland + radeon rx6600

```
./Awakened-PoE-Trade-3.17.10004.AppImage
load_input_helper [1797]: XkbGetKeyboard failed to locate a valid keyboard!
[23738:0315/120849.284379:ERROR:gpu_init.cc(441)] Passthrough is not supported, GL is swiftshader
(node:23695) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `awakened-poe-trade --trace-warnings ...` to show where the warning was created)
hook_thread_proc [101]: Could not set thread priority 49 for thread 0x7EFE92D58640!
xrecord_query [947]: XRecord is not currently available!
Аварийный останов (стек памяти сброшен на диск)
```

**Comment by SnosMe** [comment] 2022-03-15 10:08
Duplicate of #427 

Wayland is not supported.

**Closed by SnosMe** 2022-03-15 10:08 UTC
