### ISSUE TITLE
Price Checks Not Working Right

### ISSUE THREAD

**Issue by Doctor-Horrible** [SnosMe/awakened-poe-trade#435] opened 2021-07-31 19:47 UTC
![image](https://user-images.githubusercontent.com/88251970/127750890-38f6d4c9-68aa-482e-8f21-8e0f49d7abce.png)
![image](https://user-images.githubusercontent.com/88251970/127750906-5e883569-2fd5-43bb-9238-6a5055d49218.png)
This is what I show on item search...I no longer have the check boxes to adjust contributions, and the contributions show very odd...Prices are way off on all item checks.  Help, thanks!  (I am using the installed version, newest update, in windowed fullscreen on pc, and I have tried clearing out caches and whatnot and installing a fresh version x2)

**Comment by SnosMe** [comment] 2021-07-31 21:25
Duplicate of #430

**Closed by SnosMe** 2021-07-31 21:25 UTC
