### ISSUE TITLE
Contracts are no longer recognized -> "Unknown item"

### ISSUE THREAD

**Issue by SboRI** [SnosMe/awakened-poe-trade#805] opened 2022-12-19 20:49 UTC
APT no longer recognizes Contracts. Version 3.20.10002

When price checking a contract, this is the result:

Unknown Item
If this Item was introduced in this League, it will likely be supported in the next app update.
```
Item Class: Contracts
Rarity: Rare
Doom Testament
Contract: Laboratory
--------
Client: The Midnight Tinkerer
Heist Target: Hand of Arimor (Moderate Value)
Area Level: 67
Requires Counter-Thaumaturgy (Level 1 (unmet))
Item Quantity: +52% (augmented)
Item Rarity: +31% (augmented)
Alert Level Reduction: +20% (augmented)
Time Before Lockdown: +20% (augmented)
Maximum Alive Reinforcements: +20% (augmented)
--------
Item Level: 67
--------
{ Prefix Modifier "Unstoppable" (Tier: 1) — Speed }
Monsters cannot be Taunted — Unscalable Value
Monsters' Action Speed cannot be modified to below base value — Unscalable Value
{ Prefix Modifier "Supplemented" (Tier: 5) — Attack, Caster, Speed }
Reinforcements have 12(10-15)% increased Attack Speed
Reinforcements have 10(10-15)% increased Cast Speed
Reinforcements have 5(5-10)% increased Movement Speed
{ Prefix Modifier "Oppressive" (Tier: 4) }
Monsters have +20% chance to Suppress Spell Damage
(50% of Damage from Suppressed Hits and Ailments they inflict is prevented)
{ Suffix Modifier "of Rust" (Tier: 4) — Defences }
Players have 15% less Armour
Players have 10% reduced Chance to Block
--------
"Balabus Arimor was a little-known preacher during the days of Emperor Chitus,
who believed eternal life could be achieved through ritual sacrifice.
We shall see whether he was a prophet - or a charlatan."
--------
Give this Contract to Adiyah in the Rogue Harbour to emb
```

**Comment by SnosMe** [comment] 2022-12-19 23:50
Duplicate of #673 
Read there for explanation why

**Closed by SnosMe** 2022-12-19 23:50 UTC
