### ISSUE TITLE
Is this error from Awakened?

### ISSUE THREAD

**Issue by Black-Mage01** [SnosMe/awakened-poe-trade#1390] opened 2024-07-27 06:38 UTC
On Nobara 40 Linux, using the appimage with --no-overlay launch parameter
Path of Exile running through Steam with ProtonGE 9-10
Running Wayland on KDE

Sorry if this is not from this project.

![AwakenedPOETrade-JS-Error-1](https://github.com/user-attachments/assets/2603bf62-6ec1-488a-adde-b32b97c646a3)

**Comment by SnosMe** [comment] 2024-07-27 07:47
Duplicate of #993

**Closed by SnosMe** 2024-07-27 07:47 UTC
