### ISSUE TITLE
add an option for searching things on poedb.tw

### ISSUE THREAD

**Issue by wesley309** [SnosMe/awakened-poe-trade#183] opened 2020-07-16 15:00 UTC
could you make an optinos for display item on poedb instand of poewiki? 
think that poedb had a more comfortable composing for displaying item info,and sometimes got a better connection for server status.

**Comment by SnosMe** [comment] 2020-07-16 16:23
duplicate of #160

**Closed by SnosMe** 2020-07-16 16:23 UTC
