### ISSUE TITLE
Bug : "Stats ignored"

### ISSUE THREAD

**Issue by pedrolopa** [SnosMe/awakened-poe-trade#683] opened 2022-07-08 19:43 UTC
Hello

I've had this bug since I came back this league : the program doesn't recognize modifier on items - only base item and enchant/implicits. Reinstalling didn't solve it. I tried playing with setting and nothing seems to work.

Some screenshots

![Capture d’écran (14)](https://user-images.githubusercontent.com/108954984/178060198-dcb3aef3-0a5a-48cc-994a-71abd98993da.png)

![Capture d’écran (17)](https://user-images.githubusercontent.com/108954984/178060084-3c38a388-9e0b-4810-bb25-55aed4cc1a3f.png)

**Comment by SnosMe** [comment] 2022-07-08 20:18
Duplicate of #493

**Closed by SnosMe** 2022-07-08 20:18 UTC

**Comment by pedrolopa** [comment] 2022-07-08 20:42
My log file says this 

error [game-config]: Failed to read game configuration file. Default values will be used instead. {"file":"C:\\Users\\pedro\\Documents\\My Games\\Path of Exile\\production_Config.ini"}

**Comment by SnosMe** [comment] 2022-07-08 20:44
You can change PoE config file location in app settings and restart it after.
