### ISSUE TITLE
Ctrl + Alt + D graphical crashes

### ISSUE THREAD

**Issue by noraj** [SnosMe/awakened-poe-trade#384] opened 2021-05-08 15:42 UTC
Press `Ctrl + Alt + D` to check the price of the item causes graphic lags and occasionally video driver crashes since some recent updates.

**Comment by zackwheeler** [comment] 2021-05-08 15:49
same with me it crashed game on overlay open black screen poe stalls end process etc pob fork somehow closes too 5700xt radeon ryzen 3600 16gb 3600mhz ram  amd driver atm is 21.5.1

**Comment by MoshaGosha** [comment] 2021-05-08 16:29
Same. Seems to be an issue with the AMD driver 21.4.1 and upwards. It also seems to be only an issue in combination with 5700(XT) cards (not sure, but only seen it in combination with 5700XTs, if anyone is reading this with another graphics card, especially not AMD, pls say so). 

Only fix I found was installing a pre-21.4.1 driver. But 21.4.1. introduced quite a big performance boost to PoE for me, so that sucks.

**Comment by MoshaGosha** [comment] 2021-05-08 16:39
Another closed thread:
https://github.com/SnosMe/awakened-poe-trade/issues/365

They say under debug option in awakened poe trade you should enable Hardware acceleration, this should fix the issue, testing it soon and writing here what happens.

**Comment by SnosMe** [comment] 2021-05-08 17:56
Duplicate of #365 

You should update software https://github.com/SnosMe/awakened-poe-trade/issues/365#issuecomment-835256651

**Closed by SnosMe** 2021-05-08 17:56 UTC
