### ISSUE TITLE
Mac realise

### ISSUE THREAD

**Issue by Poloskunov** [SnosMe/awakened-poe-trade#395] opened 2021-05-21 09:37 UTC
Hey!

You mentioned at the end of 2020 that it is POSSIBLE to add support for the mac. Is there any chance that she will still be? Thanks

**Comment by Poloskunov** [comment] 2021-05-21 09:40
Release* sry

**Comment by SnosMe** [comment] 2021-05-21 20:42
Duplicate of #227

Nothing changed from that point, main blocker for me I don't own Mac device.

Also there were 3 different devs who wanted to add Mac support, didn't hear anything from them 😄

**Closed by SnosMe** 2021-05-21 20:42 UTC
