### ISSUE TITLE
Automatic update only 'uninstalled' 

### ISSUE THREAD

**Issue by OrdinatorStouff** [SnosMe/awakened-poe-trade#448] opened 2021-08-11 15:57 UTC
OS: Windows
Version: 2.12.1

I was playing PoE and ran a price check on something. I noticed in the overlay that there was an update available. It said it'd install on exit so I exited by right clicking on the tray icon and choosing the exit/close option. I went back to playing PoE and a moment later there was an elevation prompt for awakened poe trade installer so I allowed it and went back to playing. About 10 minutes later I went to re-open poe trade and the desktop shortcut was not working. I browsed to the folder where it was installed and the folder was completely empty. I can't find any log files to share since everything is gone and I wasn't paying any attention to the update process since I was playing but I wanted to at least make a report in case it's something worth looking into.

**Comment by SnosMe** [comment] 2021-08-12 10:44
Duplicate of #36

**Closed** 2021-08-12 10:44 UTC
