### ISSUE TITLE
Leaving price check overlay blocks Icue mouse software.

### ISSUE THREAD

**Issue by Schwanhelt** [SnosMe/awakened-poe-trade#489] opened 2021-11-03 16:52 UTC
This has started to happen since the last update and I cant quite figure out why it is.

Basically the price check overlay seems to block mouse macro inputs to the game once you click out of it to bring the game back in focus. So for instance I have my flame dash bound to Alt+T, which on my mouse is one of the side buttons, this stops functioning after doing any kind of price check and instantly starts to work again once I close out of awakened poe trade. This happens every time I use it now.

Mouse functions continue to work correctly outside of PoE, like in other games and web browsers.

It seems to me like perhaps the overlay is not focusing 100% back on the game. But I dont know.

**Comment by SnosMe** [comment] 2021-11-03 17:34
Duplicate of #477

**Closed by SnosMe** 2021-11-03 17:34 UTC
