### ISSUE TITLE
position an size of the overlay on multi monitor systems

### ISSUE THREAD

**Issue by krakel** [SnosMe/awakened-poe-trade#297] opened 2021-01-17 10:16 UTC
On my multi monitor system the overlay (shift+space or price-check) does not fit the game monitor. The overlay start on top+3cm with size to the middle of the next monitor.
I am working on linux with 3 monitors (main+top+right monitor). Can I correct the overlay position and size with configuration parameter?

**Comment by krakel** [comment] 2021-01-17 10:17
the position of the memorized cursor position is correct :)

**Comment by SnosMe** [comment] 2021-01-17 12:04
Can you attach multi-monitor screenshot, when game and price-check window shown.
Is this 3cm actually height of desktop toolbar? If so, this cannot be fixed, app sets size of full screen, but WM discards them, because... because every WM do whatever they want, and not compatible.
In regular Windowed game mode, it should work correct, can you confirm this?

**Comment by krakel** [comment] 2021-01-18 08:04
the overlay is not very visible
![awa1](https://user-images.githubusercontent.com/4434299/104887745-19da2980-596c-11eb-8411-3f117ede5658.jpg)
![awa2](https://user-images.githubusercontent.com/4434299/104887750-1cd51a00-596c-11eb-9216-2b600ac5d9bc.jpg)

**Comment by SnosMe** [comment] 2021-01-18 08:13
> In regular Windowed game mode app should work correct, can you confirm this?

**Comment by krakel** [comment] 2021-01-18 10:54
No, on pure windowed mode I get the same effect. :(

**Comment by krakel** [comment] 2021-01-18 11:02
I also renamed the .config/awakened-poe-trade folder for a fresh new configuration and start poe in windowed mode. My Linux move your overlay to this wrong position/size. :(

**Comment by SnosMe** [comment] 2021-02-20 07:25
Can't reproduce, so closing 🤷

**Closed by SnosMe** 2021-02-20 07:25 UTC
Labels: linux
