### ISSUE TITLE
Not work on Windows 7 anymore?

### ISSUE THREAD

**Issue by WirwolfCS** [SnosMe/awakened-poe-trade#911] opened 2023-04-08 14:09 UTC
Trying to instal version 3.20.10008, and after install he says that:
![ggg](https://user-images.githubusercontent.com/130231908/230725663-a460c992-68ef-4bcf-957e-ef1772324242.PNG)

**Comment by SnosMe** [comment] 2023-04-08 14:13
Duplicate of #904

**Closed by SnosMe** 2023-04-08 14:13 UTC
