### ISSUE TITLE
Item Info feature on non-map items

### ISSUE THREAD

**Issue by stamchatz** [SnosMe/awakened-poe-trade#355] opened 2021-04-20 12:00 UTC
Maybe I'm super wrong or I just haven't found it yet, but it would be amazing if we could get the Item Info shortcut to display some meaningful information about the item we hover above.
Couple examples I could think of are:
- DPS values for weapons (elem, phys, total, w/ quality)
- Combined Resistance values

The app is super cool, easy to use and customizable. Love it!
Thank you for your contribution to the community .
Cheers

**Comment by SnosMe** [comment] 2021-04-21 15:18
Duplicate of #118

**Closed by SnosMe** 2021-04-21 15:18 UTC

**Comment by SnosMe** [comment] 2021-04-21 15:20
Item info was actually called "Map check " previosly, now in the state of transitioning. UI prototype is ready, calculations haven't finished yet

**Comment by stamchatz** [comment] 2021-04-21 15:23
Thank you. Appreciate the dedication. Cheers!
