### ISSUE TITLE
[Windows 11] Key mapping: set and display incorrect when using non-qwerty layout

### ISSUE THREAD

**Issue by umbravi** [SnosMe/awakened-poe-trade#1213] opened 2023-12-22 00:44 UTC
Given a non-qwerty layout on Win11, 
When setting a key-bind,
the UI uses the qwerty key location.

This only impacts setting key-binds.
Key-bind use is correct.

Ex:
To set `ctrl+x` using Dvorak, `ctrl+q` must be pressed.

**Comment by SnosMe** [comment] 2023-12-27 14:00
Duplicate of #447

**Closed by SnosMe** 2023-12-27 14:00 UTC
