### ISSUE TITLE
Unable to start program win 10

### ISSUE THREAD

**Issue by NH4CL74656** [SnosMe/awakened-poe-trade#594] opened 2022-05-09 09:10 UTC
Hi, I am unable to get awakened poe trade running on win 10. Task manager says program is running, however, I get no icon in the tray, nor does the program show up on the desktop. No keybinds work like control d. I cant get the settings up to insert the league. Also, very oddly, I dont have a related file in %appdata% which was referred to in faq and troubleshooting.

**Comment by SnosMe** [comment] 2022-05-10 11:38
There were reports of such behavior, with empty %appdata% and only single process running in Task manager.
It has to do something with an initialization in Electron or Chromium, on which this app is built on.

Those people never answered whether they fixed it. Perhaps you will be the first to find the cause.
I am closing this issue as there is nothing I can do about it.

![image](https://user-images.githubusercontent.com/4292308/167616792-7f398881-60cc-4316-b390-7b47911265ce.png)

In normal operation, you should have 4 processes.

![image](https://user-images.githubusercontent.com/4292308/167617145-2beaaa61-5c47-4467-829d-54cd5a6c846d.png)

**Closed by SnosMe** 2022-05-10 11:38 UTC

**Comment by gagbo** [comment] 2023-04-07 14:39
I have the same issue (on Windows 10)

All I can see is that 3 processes manage to be start and be seen in the task manager. And meanwhile the mouse on desktop gets really laggy. And after that all processes get killed, and the tray icon disappears.

For the time being I tried to install for all users and install for a single user, nothing worked.
