### ISSUE TITLE
Search: all explicit mods disapeared

### ISSUE THREAD

**Issue by noraj** [SnosMe/awakened-poe-trade#433] opened 2021-07-29 16:59 UTC
The mods of flask are not appering anymore for search since PoE 3.15 (currently awakened-poe-trade v2.12.0).

![image](https://user-images.githubusercontent.com/16578570/127533886-a86fa4a4-77f5-4818-b430-96432cfbbc5b.png)

![image](https://user-images.githubusercontent.com/16578570/127533927-2e4bd633-838b-4bef-8ebd-c6339f2824f0.png)

**Comment by noraj** [comment] 2021-07-29 17:01
In fact it's not only for flask but for any items.

**Comment by noraj** [comment] 2021-07-29 17:13
It seems only implicit modifiers are still alive.

![image](https://user-images.githubusercontent.com/16578570/127535459-00c06b8c-5548-4234-a477-9ffbbb8c094e.png)

![image](https://user-images.githubusercontent.com/16578570/127535490-a70dbdc0-48b2-4468-9ebf-b0028f27547c.png)

All explicit modifiers are hidden.

**Comment by SnosMe** [comment] 2021-07-29 18:14
Duplicate of #430

**Closed by SnosMe** 2021-07-29 18:14 UTC

**Comment by noraj** [comment] 2021-07-29 22:23
I read it but didnt understand it was the same issue at first
