### ISSUE TITLE
Screen recording while streaming on Discord

### ISSUE THREAD

**Issue by Assylum123** [SnosMe/awakened-poe-trade#1215] opened 2023-12-22 12:39 UTC
When I use my hotkey for checking items while streaming on Discord something is causing my Poe Trade to start screen recording whatever screen I'm sharing. 

I have Discord Nitro so I'm not sure if that is causing it, my friends do not have the problem and they don't have Nitro so I'm not sure if that could be a cause. 

![Screenshot 2023-12-22 073823](https://github.com/SnosMe/awakened-poe-trade/assets/154603176/443f7cb6-db75-4401-9593-c5ef44658b43)
This causing a lot of pollution on my drive and I'm constantly having to delete the recordings.

**Comment by SnosMe** [comment] 2023-12-22 14:17
Duplicate of #1158

**Closed by SnosMe** 2023-12-22 14:17 UTC
