### ISSUE TITLE
3 Attribute rings are missing one attribute when searching

### ISSUE THREAD

**Issue by Juts2** [SnosMe/awakened-poe-trade#662] opened 2022-06-10 02:48 UTC
When pressing Ctrl-D to search the price of an item like this ring i've pasted below, only two of the three attributes show in the mod list (Dex and Int). The strength is not showing nor does it show in the filters when you open the trade site via the macro. 

```
Item Class: Rings
Rarity: Rare
Ghoul Finger
Two-Stone Ring
--------
Requirements:
Level: 65
--------
Item Level: 85
--------
{ Implicit Modifier — Elemental, Fire, Cold, Resistance }
+13(12-16)% to Fire and Cold Resistances (implicit)
--------
{ Prefix Modifier "Pirate's" (Tier: 3) }
15(13-18)% increased Rarity of Items found
{ Suffix Modifier "of the Wind" (Tier: 1) — Attribute }
+55(51-55) to Dexterity
{ Suffix Modifier "of the Goliath" (Tier: 4) — Attribute }
+35(33-37) to Strength
{ Suffix Modifier "of the Genius" (Tier: 1) — Attribute }
+52(51-55) to Intelligence
```

**Comment by SnosMe** [comment] 2022-06-15 20:04
This was fixed in https://github.com/SnosMe/awakened-poe-trade/releases/tag/v3.18.10003

Update app, look into hidden stats.

Duplicate of #537

**Closed by SnosMe** 2022-06-15 20:04 UTC
