### ISSUE TITLE
Trade Popups not working anymore

### ISSUE THREAD

**Issue by f0xXx3r** [SnosMe/awakened-poe-trade#566] opened 2022-03-12 05:36 UTC
Hello,

after the latest update I don't get any trade popups anymore.
Is this issue already known? I tried starting as admin; reinstall; deinstall restart system new install and restart system again...
Nothing happens..
All other functions are working nice and smooth, but only the trade popupas don't want to appear. 
Thats one of the main reasons I really like this tool, because it makes selling and trading items so much easier.

best wishes

f0xx3r

p.s. Sorry for my bad english grammar... xD

**Comment by SnosMe** [comment] 2022-03-12 09:30
Don't make guesses, check the log file instead. Duplicate of #555

**Closed by SnosMe** 2022-03-12 09:30 UTC
