### ISSUE TITLE
entry point not found

### ISSUE THREAD

**Issue by dustondan** [SnosMe/awakened-poe-trade#924] opened 2023-04-09 08:36 UTC
The procedure entry point DiscardVirtualMemory could nto be located in the dynamic link library KERNEL32.dll

windows 7

**Comment by gambitflash123** [comment] 2023-04-09 10:57
I am getting the same error on Windows 8.1, it was working for many leagues without issue.But last night after autoupdating it keeps giving me Entry Point Error.

The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library C:\Program Files\Awakened PoE Trade\Awakened PoE Trade.exe

Need help please

**Comment by SnosMe** [comment] 2023-04-09 12:31
Duplicate of #904

**Closed by SnosMe** 2023-04-09 12:31 UTC

**Comment by Smake** [comment] 2023-04-09 14:22
Try [this](https://github.com/SnosMe/awakened-poe-trade/issues/904#issuecomment-1501137181)
