### ISSUE TITLE
Whole screen overlayed in grey

### ISSUE THREAD

**Issue by Robimsel** [SnosMe/awakened-poe-trade#1230] opened 2023-12-29 19:01 UTC
When I start awakened poe trade, the whole screen gets overlayed in grey. I can move and cast spells and move items, but I can't see anything I do. 
However when I unfocus the game (for example when I'm in the browser on my second screen) the overlay hides and I can see the game. When I click into the game again, the overlay comes back.
But I can still use the trade tool to check prices or use shift+space and the menu shows up. I just can't see the game until I close the whole awakened poe trade application.
This happens in every resolution, windowed mode, fullscreen and borderless and also when poe trade is ran as an admin.

I hope my screenshots help clarifying the problem. The right third of the pictures is my second monitor

![Game Focus](https://github.com/SnosMe/awakened-poe-trade/assets/155189084/394083ac-0e44-463e-b693-45385b9da543)
![Game Overlay](https://github.com/SnosMe/awakened-poe-trade/assets/155189084/b1cacc98-f21e-40d5-8570-827b17594416)
![Game Unfocused](https://github.com/SnosMe/awakened-poe-trade/assets/155189084/b21fc9a2-3f1c-4b80-b972-ba716b32dea5)

**Comment by SnosMe** [comment] 2023-12-29 19:10
Duplicate of #1169

**Closed by SnosMe** 2023-12-29 19:10 UTC
