### ISSUE TITLE
Nove Overlay no nothing Manjaro KDE plasma

### ISSUE THREAD

**Issue by xbc1** [SnosMe/awakened-poe-trade#599] opened 2022-05-15 10:19 UTC
Hi,
used to play last league and the ones before just fine, except for some backscreen with compositor a few leagues back wich was easy to fix.
Didn't change anything since last league (wich was fine) in the PoE Settings, didn't change anything in APT Setting, didn't change OS Settings except for updates that might have fkd something idk.
https://i.imgur.com/rYXxZMl.png
Steam Overlay is disabled.

Issue:
Nothing happens.

Reproduce:
Shift + Space Ingame closes Inventory, does not trigger APT so maybe APT doesn't get any Information/Key input?

Log only 1 entry:
error [game-config]: Failed to find game configuration file in the default location. Default values will be used instead. {"file":"/home/<user>/Documents/My Games/Path of Exile/production_Config.ini"}

ctrl + alt  + c  example, seems fine: 
```
Item Class: Helmets
Rarity: Rare
Vengeance Guardian
Iron Circlet
--------
Energy Shield: 15
--------
Requirements:
Level: 16
Int: 41
--------
Sockets: B 
--------
Item Level: 9
--------
{ Prefix Modifier "Beryl" (Tier: 12) — Mana }
+16(15-19) to maximum Mana
{ Prefix Modifier "Hale" (Tier: 10) — Life }
+3(3-9) to maximum Life
{ Suffix Modifier "of Plunder" (Tier: 4) }
10(6-10)% increased Rarity of Items found
{ Suffix Modifier "of the Lizard" (Tier: 8) — Life }
Regenerate 3.3(2.1-8) Life per second
```

**Comment by SebasAren** [comment] 2022-05-15 13:59
I'm experiencing the same issue. Had the same error as @xbc1 and tried to fix it by symlinking the production_Config.ini from the steam wine prefix to the mentioned location, didn't work. It did remove the error in the log.

**Comment by weidtn** [comment] 2022-05-15 15:38
Same for Manjaro + Xmonad + Picom 
Worked before.

**Comment by SnosMe** [comment] 2022-05-15 22:51
Duplicate of #185, #428

I have no influence on the compositor.

**Closed by SnosMe** 2022-05-15 22:51 UTC

**Comment by weidtn** [comment] 2022-05-15 23:13
How is this a duplicate? I have no black screen, I have NOTHING. I had a black screen in a previous version, and was able to fix it. And when I had the black screen, I still was able to see a window in front of PoE. Now not even a window appears. This is probably not a problem of the compositor as it worked before.

**Comment by SnosMe** [comment] 2022-05-15 23:20
Other than updating the version of Electron, nothing has changed.
And as you can see, it still works in my Ubuntu VM.

**Comment by weidtn** [comment] 2022-05-16 12:48
For me it is the --no-sandbox flag in the AppImage. Without the flag I the same window as before.

**Comment by xbc1** [comment] 2022-05-16 12:58
> 

Can confirm that, removed --no-sandbox and I get an overlay.
ctrl + d = does nothing
ctrl + alt + d = opens the overlay and I can search, but it tabs out and I got to alt + tab back in.
shift + space = works as it should, but it tabs out and I got to alt + tab back in.

**Comment by SnosMe** [comment] 2022-05-16 13:05
https://security.stackexchange.com/questions/209529/what-does-enabling-kernel-unprivileged-userns-clone-do
