### ISSUE TITLE
G-Sync not working with Awakened PoE Trade

### ISSUE THREAD

**Issue by zaebokkunwow** [SnosMe/awakened-poe-trade#771] opened 2022-10-13 05:49 UTC
I have g-sync compatible monitor, poe in borderless fullscreen and when APT launched gsync not working and monitor refresh rate locked in 144.

**Comment by SnosMe** [comment] 2022-10-13 10:57
Duplicate of #709

**Closed by SnosMe** 2022-10-13 10:57 UTC
