### ISSUE TITLE
Uncheck item level by default when pricing Sextants

### ISSUE THREAD

**Issue by rushtothesun** [SnosMe/awakened-poe-trade#585] opened 2022-04-01 14:02 UTC
Item level being checked prevents pricing of Sextants (Charged Compass)

https://puu.sh/IS8HG/a00162371c.png

https://puu.sh/IS8I3/e5a07d12ae.png

**Comment by SnosMe** [comment] 2022-04-01 19:54
Duplicate of #560

**Closed by SnosMe** 2022-04-01 19:54 UTC
