### ISSUE TITLE
Awakened PoE doesn't show item mods?

### ISSUE THREAD

**Issue by pZychedelic** [SnosMe/awakened-poe-trade#588] opened 2022-04-23 03:13 UTC
It worked out normally, just tried it out and stopped showing all item mods except for base item stats like dmg armor and so on :S can't show options for specific mods on items like it used to, tried restarting everything but nothing works :S should I reinstall? just to let you know it can happen, not sure what is causing it :S

**Comment by pZychedelic** [comment] 2022-04-23 03:56
Even if I reinstall the problem still persists :S wtf is going on :S really hope we can fix it somehow

**Comment by SnosMe** [comment] 2022-04-23 10:17
Duplicate of #493

**Closed** 2022-04-23 10:18 UTC
