### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Krytyk88** [SnosMe/awakened-poe-trade#616] opened 2022-05-18 11:47 UTC
disabling anty-vir does not help
![Bez nazwy](https://user-images.githubusercontent.com/105606176/169031679-50348a5e-2656-40a2-a333-d3fa9c1710b5.png)

**Comment by SnosMe** [comment] 2022-05-18 12:07
duplicate of #383

**Closed by SnosMe** 2022-05-18 12:07 UTC
