### ISSUE TITLE
hotkeys are not set and recognized the same way

### ISSUE THREAD

**Issue by FrancoisMentec** [SnosMe/awakened-poe-trade#530] opened 2022-02-09 08:29 UTC
When you set a hotkey it always considers your keyboard has qwerty, so if I press "Ctrl+W" on an azerty the hotkey will appear as "Ctrl+Z", the issue is that when I use a hotkey it will check the actual character (the keyboard won't be considered as qwerty), so if I press the exact same hotkey that I set "Ctrl+W" it won't work. I have to press "Ctrl+Z" which isn't the key I pressed when I set the hotkey.

The solution would be to use the character of the key pressed when setting hotkeys instead of the code of the key.

I hope I made myself clear, otherwise, I'll be happy to provide more details.

Also, a side effect of this is that I can't use some hotkeys like "Ctrl+W" because I would have to press "Ctrl+Z" to set it up but if I do that the window close.

**Comment by SnosMe** [comment] 2022-02-09 09:27
Duplicate of #447

**Closed by SnosMe** 2022-02-09 09:27 UTC
