### ISSUE TITLE
Auto update on restart deleted the application and didn't install itself.

### ISSUE THREAD

**Issue by olafurw** [SnosMe/awakened-poe-trade#240] opened 2020-10-04 16:10 UTC
Got a notification that 2.5.0 was ready. I restart. It asks me if I wanna run old-installer.exe, I click ok. Nothing happens. I try to open the app again and windows says it's not there. And now the folder is empty.

**Comment by SnosMe** [comment] 2020-10-04 16:11
Duplicate of #36

**Closed by SnosMe** 2020-10-04 16:11 UTC
