### ISSUE TITLE
disables any sync

### ISSUE THREAD

**Issue by som34rus** [SnosMe/awakened-poe-trade#1044] opened 2023-08-20 19:49 UTC
disables Adaptive-Sync ,SYNC . FreeSync .in a frameless window full screen ,full screen... only works in windowed mode . I tried Steam, the usual non-Steam version. disables everywhere. windows 11 drivers all updated . maybe you can somehow solve this problem, add something to the shortcut property or to the program config?

**Comment by SnosMe** [comment] 2023-08-20 20:49
Explanation: https://github.com/SnosMe/awakened-poe-trade/issues/709#issuecomment-1224129297

You can use 
![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/a33fe6a3-1a2f-4d24-b169-8560e317a111)

on second monitor 
![image](https://github.com/SnosMe/awakened-poe-trade/assets/4292308/857ae1ea-5891-43f0-ab61-151d0932c3dd)

**Comment by som34rus** [comment] 2023-08-20 23:28
registered in the properties of the shortcut, now I have it open in the browser .Apparently I'm doing something wrong 
![Снимок экрана 2023-08-21 021521](https://github.com/SnosMe/awakened-poe-trade/assets/142749716/966bde80-7dda-4432-bb5f-72720fc5cf40)

**Comment by SnosMe** [comment] 2023-08-21 05:32
> Apparently I'm doing something wrong
Looks correct to me

**Comment by som34rus** [comment] 2023-08-21 07:48
I don't have a second monitor. and without it, it's so inconvenient (is there really nothing else that can be done?

**Comment by ParanoiaIsGreat** [comment] 2023-08-27 00:04
Is there why my whole screen flashing when using APT? 
And there is nothing I can do unless turn off any sync or open in a browser?

**Comment by aLanaMaunz** [comment] 2024-01-27 19:13
> Explanation: [#709 (comment)](https://github.com/SnosMe/awakened-poe-trade/issues/709#issuecomment-1224129297)
> 
> You can use ![image](https://private-user-images.githubusercontent.com/4292308/261875986-a33fe6a3-1a2f-4d24-b169-8560e317a111.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODI4NTgsIm5iZiI6MTcwNjM4MjU1OCwicGF0aCI6Ii80MjkyMzA4LzI2MTg3NTk4Ni1hMzNmZTZhMy0xYTJmLTRkMjQtYjE2OS04NTYwZTMxN2ExMTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMTkwOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODkzOTZkZjc1MTQ0YjU1NjQ2M2EzY2I2ZmJiZGZlZDZlNTE5NzNkYjgyNjEzMGZhMmRhNDQ5MWM2MmZhNmI3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2EqbPZcBQAjK08wC6HBPvCXYTHgZz1ulYHLVycUtTlA)
> 
> on second monitor ![image](https://private-user-images.githubusercontent.com/4292308/261876000-857ae1ea-5891-43f0-ab61-151d0932c3dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzODI4NTgsIm5iZiI6MTcwNjM4MjU1OCwicGF0aCI6Ii80MjkyMzA4LzI2MTg3NjAwMC04NTdhZTFlYS01ODkxLTQzZjAtYWI2MS0xNTFkMDkzMmMzZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjdUMTkwOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE5M2I4NDNmZDczYTczMjZlMDcyZjU5ZWI2MGUwY2RhZjk5NTY3MmI0MTdiZmIxMzc5NTgyZTA5MmZmZjU2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.m2vBGB2nq7abf68txEpdi_woKBO1Fdc1bhpZjf4mu7c)

omg - thank you!! ^-^ this is perfect, else my g-sync is not working and poe feels even more stuttery.

**Comment by SnosMe** [comment] 2024-04-07 14:45
Duplicate of #709

**Closed by SnosMe** 2024-04-07 14:45 UTC
