### ISSUE TITLE
Improved defaults while price checking charged compasses

### ISSUE THREAD

**Issue by dafillio** [SnosMe/awakened-poe-trade#573] opened 2022-03-15 22:41 UTC
Currently price checking a charged compass sets the minimum uses remaining as 1 even if it's higher than that and it sets the item level as 60 which bricks the search entirely until unselected.

Suggested:
1.  Remove selecting ilvl for charged compasses
2. Set "# uses remaining" minimum and maximum to the exact roll on the item itself.

**Comment by SnosMe** [comment] 2022-03-16 09:27
Duplicate of #560

**Closed by SnosMe** 2022-03-16 09:27 UTC
