### ISSUE TITLE
Error: Temporarily unavailable; Please use the new exchange engine

### ISSUE THREAD

**Issue by leet0rz** [SnosMe/awakened-poe-trade#611] opened 2022-05-17 01:01 UTC
Is there a fix for this?
![JhqBRQZ 1](https://user-images.githubusercontent.com/29175192/168706384-531f6a6e-94f0-4fac-b202-4a6505becfbc.png)

**Comment by dimon222** [comment] 2022-05-17 01:17
#607

**Comment by leet0rz** [comment] 2022-05-17 04:46
> #607

![s5ByK6Y 1](https://user-images.githubusercontent.com/29175192/168731066-32f06bf2-af09-4d4b-9e34-9740debc7ea2.png)
Same as in that thread

**Comment by thisVioletHydra** [comment] 2022-05-17 05:55
![image](https://user-images.githubusercontent.com/11839238/168739119-8a374b0c-9fff-4557-adda-baec5f4eda51.png)

**Comment by Discipol** [comment] 2022-05-17 09:49
This is happening for me nonstop

**Comment by githubhao0705** [comment] 2022-05-17 10:07
same error😂

**Comment by paszu** [comment] 2022-05-17 10:32
![image](https://user-images.githubusercontent.com/21226488/168791820-6e8a2d17-547b-415e-a031-f5427c5a65ac.png)

Sadly the same

**Comment by nanitll** [comment] 2022-05-17 11:43
The same :C

**Comment by jakichanka** [comment] 2022-05-17 14:36
![image](https://user-images.githubusercontent.com/43546272/168837494-7f7b243d-21e4-4d25-8ba0-833d4d381313.png)

**Comment by Pantera3370** [comment] 2022-05-17 15:01
> Is there a fix for this? ![JhqBRQZ 1](https://user-images.githubusercontent.com/29175192/168706384-531f6a6e-94f0-4fac-b202-4a6505becfbc.png)

same problem

**Comment by LMOspaceace** [comment] 2022-05-17 17:36
same issue here. thought it was something i changed but seeing this lets me know it's not lol

**Comment by Yamzball** [comment] 2022-05-17 17:56
same here :(

**Comment by msoturn** [comment] 2022-05-18 00:39
This appears to affect any items that can be bought in bulk (currency, fragments, maps, etc) and not other items.

**Comment by helpppp** [comment] 2022-05-18 01:12
{"query":{"status":{"option":"online"},"have":["chaos"],"want":["chrome"],"minimum":1222,"fulfillable":null,"collapse":true,"account":"oh"},"sort":{"have":"asc"},"engine":"new"}


Add query  -> "engine":"new" 

new json query  modify 
put this in and it will work
from Korea  ^^

**Comment by msoturn** [comment] 2022-05-18 01:30
> {"query":{"status":{"option":"online"},"have":["chaos"],"want":["chrome"],"minimum":1222,"fulfillable":null,"collapse":true,"account":"oh"},"sort":{"have":"asc"},"engine":"new"}
> 
> Add query -> "engine":"new"
> 
> new json query modify put this in and it will work

If you check for update on your taskbar, the issue seems to be fixed in an update.

**Comment by Nickakanickiam** [comment] 2022-05-18 09:04
Not for me.

**Comment by SnosMe** [comment] 2022-05-18 12:09
This has been fixed.

**Closed by SnosMe** 2022-05-18 12:09 UTC

**Comment by nebucadneza** [comment] 2022-05-18 16:41
had same issue when i updated.
uninstalled and reinstalled fresh and now the issue is gone
