### ISSUE TITLE
Inside Awakened PoE Trade Item Site Searching

### ISSUE THREAD

**Issue by Pumbees** [SnosMe/awakened-poe-trade#851] opened 2023-01-05 14:08 UTC
Hi Snowsme: So I used to be able to use a browser inside the game through Awakened PoE Trade which I liked. I Found that I can open in browser through tray app, but Its not the same because it required me to open a whole browser in google, its not the same. It used to be able to do searches and not have to open a browser, i could just do searches inside Awakened, is this option still available, because I would like to leave my browser's closed and just use the old Awakened PoE Trade option to search the website without having EDGE or Google Chrome open. It was nice and convenient. Now the only option I have is using a browser engine instead of awakened poe trade website inside your app which I miss.

I have no use to open things in new browser outside program, id like to keep the searches within... ;/

**Comment by SnosMe** [comment] 2023-01-05 14:30
Duplicate of #821

**Closed by SnosMe** 2023-01-05 14:30 UTC
