### ISSUE TITLE
Hacvng issues, no stats, not recognized mod

### ISSUE THREAD

**Issue by Gazuntight** [SnosMe/awakened-poe-trade#353] opened 2021-04-18 22:58 UTC
![No stats](https://user-images.githubusercontent.com/82783895/115163606-fceee880-a077-11eb-8f86-f35ad5823436.png)
![NOT rec](https://user-images.githubusercontent.com/82783895/115163608-fe201580-a077-11eb-9c88-009a497c47c7.png)

**Comment by superness** [comment] 2021-04-19 00:33
Same no item stats are detected for the search

**Comment by SnosMe** [comment] 2021-04-19 06:38
Duplicate of #351

This should be fixed if you update **PoE client** and app to v2.10.1

**Closed by SnosMe** 2021-04-19 06:38 UTC

**Comment by Gazuntight** [comment] 2021-04-19 15:47
Thanks for the reply, I am currently using updated versions of both, I have reinstalled both POE and trade macro, I am still having NOT RECOGNIZED MODS pop up. No idea why.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
