### ISSUE TITLE
Put a manual search button. Do not auto search ever

### ISSUE THREAD

**Issue by Juts2** [SnosMe/awakened-poe-trade#314] opened 2021-01-26 20:26 UTC
GGG going to keep disabling this tool if you dont disable the auto searching 0.2 seconds after a value is tweaked 

Every single search should be manual.

**Comment by SengitU** [comment] 2021-01-27 08:11
I love using this application @SnosMe , thanks to everyone who has worked on it.
I can try to take this as soon as my working day is over, in approximately 9 hours. Do you think implementing this would make sense? Or if you're already working on such a feature it would be meaningless. Please let me know.

**Comment by SnosMe** [comment] 2021-01-27 10:38
I'll ship some optimizations in next release. I understand that you guys want to help, but prefer to implement what's on my mind first and then will review ideas/advices you have. Expect release on ~Saturday

**Comment by SengitU** [comment] 2021-01-27 11:34
> I'll ship some optimizations in next release. I understand that you guys want to help, but prefer to implement what's on my mind first and then will review ideas/advices you have. Expect release on ~Saturday

Thanks for the reply, I appreciate the tool you created and I'm looking forward to use it again (but no-pressure 😅 ).

**Comment by SengitU** [comment] 2021-02-04 13:14
Looks like you've provided a solution for this one, thanks @SnosMe .

**Comment by SnosMe** [comment] 2021-02-19 21:33
Duplicate of #273

**Closed by SnosMe** 2021-02-19 21:33 UTC
