### ISSUE TITLE
Auto update nukes install

### ISSUE THREAD

**Issue by Cephel** [SnosMe/awakened-poe-trade#155] opened 2020-06-30 22:52 UTC
What happens:

1. I close the app
2. old-uninstaller.exe requesting elevated permissions
3. Installation folder is now empty
![image](https://user-images.githubusercontent.com/6716857/86184805-2ebcb000-bb35-11ea-8db7-7e60f43c3df4.png)

**Comment by SnosMe** [comment] 2020-06-30 22:54
Duplicate of #36

**Closed by SnosMe** 2020-06-30 22:54 UTC
